WITH SUB3 AS (

WITH SUB2 AS (

WITH SUB AS (
SELECT 
	
	DISTINCT UPPER(CASE 
		WHEN UPPER(A.NAME) IS NULL THEN UPPER(P.NAME)
		WHEN UPPER(P.NAME) IS NULL THEN UPPER(A.NAME)
		WHEN UPPER(A.NAME) = UPPER(P.NAME) THEN UPPER(A.NAME)
		WHEN UPPER(P.NAME) = UPPER(A.NAME) THEN UPPER(P.NAME)
		END) 
			AS ALL_APPS,
	
	CASE 
		WHEN UPPER(A.NAME) = UPPER(P.NAME) THEN 'BOTH_STORES'
		WHEN UPPER(A.NAME) IS NULL THEN 'PLAY_STORE'
		WHEN UPPER(P.NAME) IS NULL THEN 'APP_STORE'
		ELSE 'XYZZZZZ'
		END 
			AS LOCATION,
	
	CAST(A.PRICE AS MONEY) AS PRICE_A,
	CAST(P.PRICE AS MONEY) AS PRICE_P,
	
	CAST(A.RATING AS NUMERIC(2, 1)) AS A_RATING,
	CAST(P.RATING AS NUMERIC(2, 1)) AS P_RATING
	
FROM 
	APP_STORE_APPS AS A
FULL JOIN 
	PLAY_STORE_APPS AS P
ON UPPER(P.NAME) = UPPER(A.NAME)
ORDER BY LOCATION DESC
	)--END SUB

SELECT
	ALL_APPS, LOCATION,
	CASE
		WHEN PRICE_A IS NULL THEN PRICE_P
		WHEN PRICE_P IS NULL THEN PRICE_A
		WHEN PRICE_A > PRICE_P THEN PRICE_A
		WHEN PRICE_A < PRICE_P THEN PRICE_P
		WHEN PRICE_A = PRICE_P THEN PRICE_A
		ELSE '99999999' 
		END
			AS PRICE_COMBINED,
	A_RATING, P_RATING,
	CASE
		WHEN A_RATING IS NULL THEN P_RATING
		WHEN P_RATING IS NULL THEN A_RATING
		WHEN P_RATING = A_RATING THEN P_RATING
		WHEN A_RATING > P_RATING THEN ROUND((A_RATING + P_RATING) / 2.0 * 2) / 2.0
		WHEN A_RATING < P_RATING THEN ROUND((A_RATING + P_RATING) / 2.0 * 2) / 2.0
		END
			AS RATING_COMBINED--REGULAR RATINGS
	
FROM 
	SUB
ORDER BY PRICE_COMBINED DESC
)

SELECT
	ALL_APPS, /*PRICE_COMBINED, LOCATION, RATING_COMBINED, */
	
	CASE 
    	WHEN LOCATION = 'BOTH' THEN (PRICE_COMBINED::numeric * 10000)::money
    	ELSE (PRICE_COMBINED::numeric * 10000)::money
		END 
			AS PURCHASE_PRICE,
			
	CAST(1000 AS MONEY) AS MARKETING_SPEND,
	
	CASE
		WHEN LOCATION = 'BOTH' THEN CAST(10000 AS MONEY)
		ELSE CAST(5000 AS MONEY)
		END	
			AS MONTHLY_EARNINGS,
			
	(RATING_COMBINED * 2) + 1 
			AS PROJECTED_LIFESPAN
	
FROM
	SUB2
	)
	
SELECT
	
	ALL_APPS, PURCHASE_PRICE, MARKETING_SPEND, MONTHLY_EARNINGS, PROJECTED_LIFESPAN,
	
	((MONTHLY_EARNINGS - MARKETING_SPEND) * PROJECTED_LIFESPAN) - PURCHASE_PRICE 
		AS NET_PROFIT
	
FROM 
	SUB3
ORDER BY NET_PROFIT DESC